### PR TITLE
Correct very small typo

### PR DESCRIPTION
**Pull request by TopperDEL**
Double occurence of "that"

### CODE REVIEW

**Comment by ghuntley** [comment]
@all-contributors please add @TopperDEL

**Comment by ghuntley** [comment]
@all-contributors please add @TopperDEL for docs

**Comment by ghuntley** [comment]
Thanks @TopperDEL <3. Can you leave your digits over at https://platform.uno/uno-is-joining-hacktoberfest-2019/ and we'll send you some swag!

**Comment by TopperDEL** [comment]
Thanks. That change Was so small, feel a little Bad to get swag for it. I'll See if I can contribute a bit more to the awesome project!

**Pull request merged**
